services:
  - type: web
    name: skintel-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDirectory: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
    healthCheckPath: /api/scheduler/status